// Copyright 2017 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_combine6                         7
#define gattdb_protocol_mode                   19
#define gattdb_report                          21
#define gattdb_client_characteristic_configuration         22
#define gattdb_report_reference                23
#define gattdb_report_map                      25
#define gattdb_external_report_reference         26
#define gattdb_boot_keyboard_input_report         28
#define gattdb_client_characteristic_configuration         29
#define gattdb_boot_keyboard_output_report         31
#define gattdb_boot_mouse_input_report         33
#define gattdb_client_characteristic_configuration         34
#define gattdb_hid_information                 36
#define gattdb_hid_control_point               38
#define gattdb_ota_control                     41
#define gattdb_ota_data                        43

#endif
