################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
MSA_UPPER_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
MSA_SRCS := 
O_SRCS := 
ASM_UPPER_DEPS := 
MSA_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
ASM_DEPS := 
S79_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
MSA_DEPS := 
C_DEPS := 
S79_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
app/application \
app/application/tau/kinetic/filters \
app/application/tau/kinetic \
app/application/tau/kinetic/qmath \
app/application/tau \
app/bluetooth/common/util \
app \
app/peripherals/drivers/hapticcontroller \
app/peripherals/sensors/batterymonitor \
app/peripherals/sensors/motionsensor \
app/peripherals/sensors/rhoclient \
app/rtos/uC-CPU/ARC/EM6/MetaWare \
app/rtos/uC-CPU/ARM/GNU \
app/rtos/uC-CPU/ARM/IAR \
app/rtos/uC-CPU/ARM/RealView \
app/rtos/uC-CPU/ARM-Cortex-A/ARMv7-A/ARM \
app/rtos/uC-CPU/ARM-Cortex-A/ARMv7-A/CCS \
app/rtos/uC-CPU/ARM-Cortex-A/ARMv7-A/GNU \
app/rtos/uC-CPU/ARM-Cortex-A/ARMv7-A/IAR \
app/rtos/uC-CPU/ARM-Cortex-A/ARMv8-A/ARM \
app/rtos/uC-CPU/ARM-Cortex-A/ARMv8-A/GNU \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv6-M/ARM \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv6-M/GNU \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv6-M/IAR \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv6-M \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv7-M/ARM \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv7-M/CCS \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv7-M/GNU \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv7-M/IAR \
app/rtos/uC-CPU/ARM-Cortex-M/ARMv7-M \
app/rtos/uC-CPU/ARM-Cortex-R/ARMv7-R/ARM \
app/rtos/uC-CPU/ARM-Cortex-R/ARMv7-R/CCS \
app/rtos/uC-CPU/ARM-Cortex-R/ARMv7-R/GNU \
app/rtos/uC-CPU/ARM-Cortex-R/ARMv7-R/IAR \
app/rtos/uC-CPU/AVR/ATxmega128/GNU \
app/rtos/uC-CPU/AVR32/AP7000/GNU \
app/rtos/uC-CPU/AVR32/AP7000/IAR \
app/rtos/uC-CPU/AVR32/UC3/AtmelStudio6 \
app/rtos/uC-CPU/AVR32/UC3/GNU \
app/rtos/uC-CPU/AVR32/UC3/IAR \
app/rtos/uC-CPU/BSP/Template \
app/rtos/uC-CPU/Blackfin/VDSP++ \
app/rtos/uC-CPU/C28x/CCS \
app/rtos/uC-CPU/Cache/ARC/EM6 \
app/rtos/uC-CPU/Cache/ARM/armv5_generic_l1/IAR \
app/rtos/uC-CPU/Cache/ARM/armv5_generic_l1 \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1/ARM \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1/GNU \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1/IAR \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1 \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1_l2c310_l2/ARM \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1_l2c310_l2/GNU \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1_l2c310_l2/IAR \
app/rtos/uC-CPU/Cache/ARM/armv7_generic_l1_l2c310_l2 \
app/rtos/uC-CPU/Cache/ARM/armv7m_generic_l1 \
app/rtos/uC-CPU/Cache/Freescale/Kinetis \
app/rtos/uC-CPU/Cache/NXP/powerpc_e200z4204n3/GNU \
app/rtos/uC-CPU/Cache/NXP/powerpc_e200z4204n3 \
app/rtos/uC-CPU/Cache/NiosII \
app/rtos/uC-CPU/ColdFire/Generic/CW_For_Microcontrollers \
app/rtos/uC-CPU/ColdFire/Generic/Codewarrior \
app/rtos/uC-CPU/ColdFire/Generic/IAR \
app/rtos/uC-CPU/EnSilica/eSi-3250/EDS \
app/rtos/uC-CPU/FR/Softune \
app/rtos/uC-CPU/LatticeMico32/GNU \
app/rtos/uC-CPU/M14K/CodeSourcery \
app/rtos/uC-CPU/MC9S08/NonPaged/Codewarrior \
app/rtos/uC-CPU/MC9S08/Paged/Codewarrior \
app/rtos/uC-CPU/MC9S12/Codewarrior/NonPaged \
app/rtos/uC-CPU/MC9S12/Codewarrior \
app/rtos/uC-CPU/MC9S12X/Codewarrior \
app/rtos/uC-CPU/MCF5272/GNU \
app/rtos/uC-CPU/MIPS32-4K/MPLAB-PIC32-GCC \
app/rtos/uC-CPU/MPC55xx/CodeWarrior \
app/rtos/uC-CPU/MPC55xx-VLE/CodeWarrior \
app/rtos/uC-CPU/MPC56xx/CodeWarrior \
app/rtos/uC-CPU/MPC56xx-VLE/CodeWarrior \
app/rtos/uC-CPU/MPC57xx-VLE/GNU \
app/rtos/uC-CPU/MPC8349E/CodeWarrior \
app/rtos/uC-CPU/MicroBlaze/GNU \
app/rtos/uC-CPU/NiosII/GNU \
app/rtos/uC-CPU/PPC405/GNU \
app/rtos/uC-CPU/Posix/GNU \
app/rtos/uC-CPU/RISC-V/GCC \
app/rtos/uC-CPU/RL78/GNURL78 \
app/rtos/uC-CPU/RX/GNURX \
app/rtos/uC-CPU/RX610/GNURX \
app/rtos/uC-CPU/Template \
app/rtos/uC-CPU/V850E2M/CubeSuite+ \
app/rtos/uC-CPU/V850ES/CubeSuite \
app/rtos/uC-CPU/V850ES/PM+ \
app/rtos/uC-CPU/Win32/Visual_Studio \
app/rtos/uC-CPU \
app/rtos/uC-LIB/Ports/ARM/GNU \
app/rtos/uC-LIB/Ports/ARM/IAR \
app/rtos/uC-LIB/Ports/ARM/RealView \
app/rtos/uC-LIB/Ports/ARM-Cortex-M1/RealView \
app/rtos/uC-LIB/Ports/ARM-Cortex-M3/GNU \
app/rtos/uC-LIB/Ports/ARM-Cortex-M3/IAR \
app/rtos/uC-LIB/Ports/ARM-Cortex-M3/RealView \
app/rtos/uC-LIB/Ports/ARM-Cortex-M4/GNU \
app/rtos/uC-LIB/Ports/ARM-Cortex-M4/IAR \
app/rtos/uC-LIB/Ports/ARM-Cortex-M4/RealView \
app/rtos/uC-LIB/Ports/AVR32/AP7000/IAR \
app/rtos/uC-LIB/Ports/AVR32/UC3/GNU \
app/rtos/uC-LIB \
app/rtos/uC-OS3/Cfg/Template \
app/rtos/uC-OS3/Ports/ARC/EM6/MetaWare \
app/rtos/uC-OS3/Ports/ARM/Generic/IAR \
app/rtos/uC-OS3/Ports/ARM/Generic/RealView \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv7-A/ARM \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv7-A/CCS \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv7-A/GNU \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv7-A/IAR \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv7-A \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv8-A/GNU \
app/rtos/uC-OS3/Ports/ARM-Cortex-A/ARMv8-A \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv6-M/ARM \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv6-M/GNU \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv6-M/IAR \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv6-M \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv7-M/ARM \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv7-M/CCS \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv7-M/GNU \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv7-M/IAR \
app/rtos/uC-OS3/Ports/ARM-Cortex-M/ARMv7-M \
app/rtos/uC-OS3/Ports/ARM-Cortex-R/ARMv7-R/ARM \
app/rtos/uC-OS3/Ports/ARM-Cortex-R/ARMv7-R/CCS \
app/rtos/uC-OS3/Ports/ARM-Cortex-R/ARMv7-R/GNU \
app/rtos/uC-OS3/Ports/ARM-Cortex-R/ARMv7-R/IAR \
app/rtos/uC-OS3/Ports/ARM-Cortex-R/ARMv7-R \
app/rtos/uC-OS3/Ports/AVR/ATxmega128/IAR \
app/rtos/uC-OS3/Ports/AVR32/AP7000/IAR \
app/rtos/uC-OS3/Ports/AVR32/UC3/AtmelStudio6 \
app/rtos/uC-OS3/Ports/AVR32/UC3/IAR \
app/rtos/uC-OS3/Ports/Blackfin/VDSP++ \
app/rtos/uC-OS3/Ports/C28x/Generic/CCS \
app/rtos/uC-OS3/Ports/ColdFire-EMAC/Generic/CodeWarrior \
app/rtos/uC-OS3/Ports/Coldfire/Generic/CW_For_Microcontrollers \
app/rtos/uC-OS3/Ports/Coldfire/Generic/CodeWarrior \
app/rtos/uC-OS3/Ports/Coldfire/Generic/IAR \
app/rtos/uC-OS3/Ports/EnSilica/eSi-3250/EDS \
app/rtos/uC-OS3/Ports/HCS12/Paged/CodeWarrior \
app/rtos/uC-OS3/Ports/M14K/CodeSourcery \
app/rtos/uC-OS3/Ports/MIPS32-4K/Vectored-Interrupt/MPLAB-PIC32-GCC \
app/rtos/uC-OS3/Ports/MSP430X/IAR/MSP430x5xx \
app/rtos/uC-OS3/Ports/MicroBlaze/GNU \
app/rtos/uC-OS3/Ports/Microchip/PIC24FJ128/C30 \
app/rtos/uC-OS3/Ports/POSIX/GNU \
app/rtos/uC-OS3/Ports/PPC405/GNU \
app/rtos/uC-OS3/Ports/PowerPC/MPC57xx-VLE/GNU \
app/rtos/uC-OS3/Ports/RISC-V/RV32/GCC \
app/rtos/uC-OS3/Ports/Renesas/78K0R/IAR \
app/rtos/uC-OS3/Ports/Renesas/RL78/GNURL78 \
app/rtos/uC-OS3/Ports/Renesas/RL78/IAR \
app/rtos/uC-OS3/Ports/Renesas/RX/GNURX \
app/rtos/uC-OS3/Ports/Renesas/RX/IAR \
app/rtos/uC-OS3/Ports/Renesas/RX/RXC \
app/rtos/uC-OS3/Ports/Renesas/SH2A-Banked/HEW \
app/rtos/uC-OS3/Ports/Renesas/SH2A-FPU/HEW \
app/rtos/uC-OS3/Ports/Renesas/SH2A-FPU-Banked/HEW \
app/rtos/uC-OS3/Ports/Renesas/V850E2M/CubeSuite+ \
app/rtos/uC-OS3/Ports/Renesas/V850E2M/IAR \
app/rtos/uC-OS3/Ports/Renesas/V850E2S/IAR \
app/rtos/uC-OS3/Ports/Renesas/V850ES/IAR \
app/rtos/uC-OS3/Ports/Template \
app/rtos/uC-OS3/Ports/Win32/Visual_Studio \
app/rtos/uC-OS3/Source \
app/rtos/uC-OS3/TLS/CCES \
app/rtos/uC-OS3/TLS/IAR \
app/rtos/uC-OS3/TLS/NewLib \
app/system/core \
app/system/interfaces \
app/system/sysiocontroller \
. \
hardware/kit/common/bsp \
hardware/kit/common/drivers \
platform/Device/SiliconLabs/EFR32BG13P/Source/IAR \
platform/Device/SiliconLabs/EFR32BG13P/Source \
platform/emdrv/sleep/src \
platform/emlib/src \
platform/service/sleeptimer/src \
protocol/bluetooth/lib/EFR32BG13P/IAR \

