################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
MSA_UPPER_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
MSA_SRCS := 
O_SRCS := 
ASM_UPPER_DEPS := 
MSA_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
ASM_DEPS := 
S79_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
MSA_DEPS := 
C_DEPS := 
S79_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
app/application \
app/application/tau/kinetic/filters \
app/application/tau/kinetic \
app/application/tau/kinetic/qmath \
app/application/tau \
app/bluetooth/common/util \
app \
app/peripherals/drivers/hapticcontroller \
app/peripherals/sensors/batterymonitor \
app/peripherals/sensors/motionsensor \
app/peripherals/sensors/rhoclient \
app/rtos/Source \
app/rtos/Source/portable/IAR/78K0R \
app/rtos/Source/portable/IAR/ARM_CA5_No_GIC \
app/rtos/Source/portable/IAR/ARM_CA9 \
app/rtos/Source/portable/IAR/ARM_CM0 \
app/rtos/Source/portable/IAR/ARM_CM3 \
app/rtos/Source/portable/IAR/ARM_CM4F \
app/rtos/Source/portable/IAR/ARM_CM4F_MPU \
app/rtos/Source/portable/IAR/ARM_CM7/r0p1 \
app/rtos/Source/portable/IAR/ARM_CRx_No_GIC \
app/rtos/Source/portable/IAR/ATMega323 \
app/rtos/Source/portable/IAR/AVR32_UC3 \
app/rtos/Source/portable/IAR/AtmelSAM7S64 \
app/rtos/Source/portable/IAR/AtmelSAM9XE \
app/rtos/Source/portable/IAR/LPC2000 \
app/rtos/Source/portable/IAR/MSP430 \
app/rtos/Source/portable/IAR/MSP430X \
app/rtos/Source/portable/IAR/RL78 \
app/rtos/Source/portable/IAR/RX100 \
app/rtos/Source/portable/IAR/RX600 \
app/rtos/Source/portable/IAR/RXv2 \
app/rtos/Source/portable/IAR/STR71x \
app/rtos/Source/portable/IAR/STR75x \
app/rtos/Source/portable/IAR/STR91x \
app/rtos/Source/portable/IAR/V850ES \
app/rtos/micrium_os/bsp/siliconlabs/generic/source \
app/rtos/micrium_os/common/source/collections \
app/rtos/micrium_os/common/source/common \
app/rtos/micrium_os/common/source/kal \
app/rtos/micrium_os/common/source/lib \
app/rtos/micrium_os/common/source/platform_mgr \
app/rtos/micrium_os/common/source/rtos \
app/rtos/micrium_os/cpu/source \
app/rtos/micrium_os/kernel/source \
app/rtos/micrium_os/ports/source/generic \
app/rtos/micrium_os/ports/source/iar \
app/system/core \
app/system/interfaces \
app/system/sysiocontroller \
. \
hardware/kit/common/bsp \
hardware/kit/common/drivers \
platform/Device/SiliconLabs/EFR32BG13P/Source/IAR \
platform/Device/SiliconLabs/EFR32BG13P/Source \
platform/emdrv/sleep/src \
platform/emlib/src \
platform/service/sleeptimer/src \
protocol/bluetooth/lib/EFR32BG13P/IAR \

